### ISSUE TITLE
Trouble running on Windows

### ISSUE THREAD

**Issue by khalid-hussain** [raghur/mermaid-filter#1]
Hi there,

I wish to use this filter on a Windows machine but am having some trouble using it. I was able to install all the required modules using npm.

After running the given command, I get the following error:
```
pandoc.exe: Filter mermaid-filter not found
```

I think this may not be actually related to the plugin itself, but some help would be appreciated.

Thanks for your time.

**Comment by raghur** [comment]
Are you sure you installed `mermaid-filter` itself? What happens when you type in `mermaid-filter` in cmd.exe. Here's sample output I get to confirm that it's indeed installed. Also make sure you use the `--global` flag when installing.

```


C:\Users\xxxxxxx>npm install --global raghur/mermaid-filter
C:\Users\xxxxxxx\AppData\Roaming\npm\mermaid-filter -> C:\Users\xxxxxxxxxxxx\AppData\Roaming\npm\node_modules\mermaid-filter\index.js
mermaid-filter@0.0.1 C:\Users\xxxxxxxxxxxxxx\AppData\Roaming\npm\node_modules\m
ermaid-filter
├── pandoc-filter@0.1.2 (get-stdin@0.1.0)
└── tmp@0.0.28 (os-tmpdir@1.0.1)

C:\Users\xxxxxxxxxxxx>mermaid-filter.cmd
^CTerminate batch job (Y/N)? y
```

**Comment by khalid-hussain** [comment]
Yes I'm sure it's installed.

![cmd-mermaid](https://cloud.githubusercontent.com/assets/3102714/11501829/12e24b6e-9872-11e5-93ac-d65988dd9744.png)

**Comment by raghur** [comment]
Ok - so I tried it out on Windows and looks like specifying the filter as `-F mermaid-filter.cmd` works. Can you try that?

**Comment by khalid-hussain** [comment]
Perfect, it works!

Thanks a lot. I think this should be highlighted in the README?

**Comment by raghur** [comment]
updated in README
