### ISSUE TITLE
list of options?

### ISSUE THREAD

**Issue by kurokirasama** [raghur/mermaid-filter#100]
Is there documentation about the options that can be put here:
```
{.mermaid options...}
```

like `#fig:diag1`, caption=` , `theme=` and `background=`?

**Comment by glgoose** [comment]
## example usage

    ```{.mermaid width=100 format=png loc=img}
     sequenceDiagram
        Alice->>John: Hello John, how are you?
        John-->>Alice: Great!
    ```
Taken from: https://github.com/raghur/mermaid-filter/blob/master/test.md?plain=1#L5-L9

## options

option   | default 
--------| -------
width    | 800
format  | png
loc        | inline
theme  | default
background | white
caption  | ''
filename | ''
scale      | 1
imageClass | ''
 
Code reference: https://github.com/raghur/mermaid-filter/blob/97075a3988b25c24593c17e5282280627d0eaf4d/index.js#L29-L37
