### ISSUE TITLE
Publishing a new NPM release

### ISSUE THREAD

**Issue by balaji-dutt** [raghur/mermaid-filter#102]
Hi,

The latest release in the repo and the npm index is from March 2022. I see that there have been a number of changes to the code and the dependency versions in the repo but there is no release to npm.

I've been patching in some changes and version upgrades that I require by hand, but it would be great if there was an actual updated release to npm. Would this be possible?

**Comment by raghur** [comment]
This repo is still alive... in any case, I've pushed out a new rel to npm with deps updates that were sitting without a release
