### ISSUE TITLE
configure mermaid diagram

### ISSUE THREAD

**Issue by agusmba** [raghur/mermaid-filter#16]
Would it be possible to configure somehow the mermaid diagram?

I'm thinking specifically about the mirrorActor(s?) option in [sequence diagrams](https://mermaidjs.github.io/sequenceDiagram.html)

Other useful options that would be nice to be able to configure are the actor box size... See https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js

Thanks!!

**Comment by raghur** [comment]
https://mermaidjs.github.io/sequenceDiagram.html says

>Is it possible to adjust the margins for rendering the sequence diagram.

>This is done by defining mermaid.sequenceConfig or by the CLI to use a json file with the configuration. How to use the CLI is described in the mermaidCLI page. 

but the new CLI tool project doesn't expose a way to pass in the config object/json. I currently depend on the CLI tool to call mermaid (not using the api).

Will check later if the cli has an undocumented arg to give a config json.

**Comment by agusmba** [comment]
I opened https://github.com/mermaidjs/mermaid.cli/issues/9 in order to track it.

**Comment by agusmba** [comment]
Version 0.3.1 of mermaid.cli now supports configuration via json file (and css file for extra config!)

**Comment by raghur** [comment]
Great... How do you think this should be supported on mermaid-filter? We could do additional options on the mermaid class - but this means that every diagram on the markdown file needs the class to be specified. 
Also, reduces portability - for ex if you render on a different machine where the config files arent available.

I think having `.mermaid-filter-config.json` and `.mermaid-filter.css` files in the folder from where pandoc is run might be better?

Thoughts?

**Comment by agusmba** [comment]
Mmmm, thinking aloud here.

I'm not sure if having the config files where the pandoc binary is run is a good idea. I guess it would be ok if a default configuration set of files was installed in the right place when doing the `npm install --global mermaid-filter`

Another option would be having a couple of vscode configuration entries pointing to where the mermaid-filter-config.json and .css are. This would allow you to have self-contained pandoc projects, with the configuration files in it. In case these configuration entries are empty, you could have the pandoc directory as default...

Any of these would make *all* your diagrams render the same way, or at least all your project diagrams (since vscode config can change at the project level, right?), but I think this could be an acceptable compromise.

**Comment by raghur** [comment]
>Another option would be having a couple of vscode configuration entries pointing to where the mermaid-filter-config.json and .css are. This would allow you to have self-contained pandoc projects, with the configuration files in it. In case these configuration entries are empty, you could have the pandoc directory as default...

I don't want to tie mermaid-filter to vscode specific configuration (though I'm not sure if that's what you mean)

What I meant is that if you have ~/folderA which has a bunch of markdown files, and assuming most people run pandoc inside ~/folderA, then look for the default config files in folderA - which seems pretty much what you're suggesting in the latter part.

**Comment by agusmba** [comment]
> I don't want to tie mermaid-filter to vscode specific configuration (though I'm not sure if that's what you mean)

Yes, that's what I meant, and you are completely right. The filter should stand on its own. Forget what I said about vscode.

> What I meant is that if you have ~/folderA which has a bunch of markdown files, and assuming most people run pandoc inside ~/folderA, then look for the default config files in folderA - which seems pretty much what you're suggesting in the latter part.

Sounds reasonable. I'd go for this one.

Can filters receive parameters to specify alternate locations?

**Comment by raghur** [comment]
I just pushed a branch - jsonconfig - can you pull from there and give it a go?

>Can filters receive parameters to specify alternate locations?

AFAICR, not if you specify the the filtername as `-F` to pandoc. You have to write out the entire command like
`pandoc -t json -i somefile.md | node index.js -opta --opt | pandoc -t html -o whatever.html`

and that's quite cumbersome.

**Comment by agusmba** [comment]
Certainly.

Any recommendation on how to install the devel version (or make it accesible to pandoc as a filter)?

**Comment by raghur** [comment]
you can install it with npm - like so 

`user/project#branch` - so `npm i -g raghur/mermaid-filter#jsonconfig`

**Comment by agusmba** [comment]
Thanks!

Testing...

I'll update this post after the tests.

**Comment by agusmba** [comment]
Pandocomatic works fine also.

I must say this is a fantastic improvement, I will finally be able to use mermaid for generating docx documents, and have them look great.

**Comment by agusmba** [comment]
Now that I review mermaid.cli, the only thing that is missing is the `--theme` option (the background one can be simulated with the css config).

Maybe the theme option can also be replicated with the css+json config, but it would be nice to have it also in the filter.

Should I open a separate issue for it?

**Comment by raghur** [comment]
Just pushed to jsonconfig branch with support for `--theme`. README has been updated as well - so take a look there.

**Comment by agusmba** [comment]
It works great!

It has even allowed me to find a couple of bugs in mermaid.cli (I made a new PR there to fix them https://github.com/mermaidjs/mermaid.cli/pull/21 )

Thanks @raghur

**Comment by raghur** [comment]
Great... thanks for testing. Have merged and pushed out v1.1.0 to npm

**Comment by agusmba** [comment]
Only one question.

The PR above is trying to fix mermaid.cli when no theme is specified in the commandline, but a theme is present in the json config (right now default theme is always used).

I fear the same would happen in this filter.

Would it be possible to only specify `-t default` if the theme was explicitly entered as an attribute to the figure?

It could be done by setting a default value different from "default" (like "theme-default") and only issuing the `-t` commandline when the value was different from this "theme-default".

I was writing this as you closed the issue.

No worries, we could revisit this if/when  my PR is merged in mermaid.cli

Thanks for pushing 1.1.0 !!!!
