### ISSUE TITLE
Did pandoc change their json representation recently?

### ISSUE THREAD

**Issue by manor** [raghur/mermaid-filter#2]
I'm getting this even if I use your copy of pandoc-filter:
```
pandoc: When expecting a product of 3 values, encountered an Array of 2 elements instead

**Comment by raghur** [comment]
what version of pandoc are you on?

**Comment by manor** [comment]
pandoc 1.16 -- I think the issue is the addition of `link_attributes`... Since I am more comfortable with Python I modified the the [graphviz  filter example](https://github.com/jgm/pandocfilters/blob/master/examples/graphviz.py) to make a mermaid filter, which is funny when you think about the language mix (haskell for pandoc itself, python for the filters and javascript for the mermaidjs :-)

**Comment by raghur** [comment]
That's exactly the issue. However, looks like I also need to fix this upstream on `pandoc-filter-node`. It's minor and I'll send a PR there.

**Comment by raghur** [comment]
Upstream PR was merged and I've updated package.json dependency. THings should be good now. If you can, can you do a quick test?

**Comment by josephwinston** [comment]
Same issue here @raghur .  Using ```commit 99a7f7637026161988e86d2a4f51cf578e8cf818``` for mermaid-filter.  ```npm install --global phantomjs@1.9.0-6``` since using ```npm install --global phantomjs-prebuilt``` causes

```
You had errors in your syntax. Use --help for further information.
mermaid requires phantomjs ^1.9.0 to be installed, found version 2.1.1

fs.js:729
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

```

**Comment by raghur** [comment]
Hmm - I'm not able to repro this

here's my setup
```
raghu@desktop:~/code/mermaid-filter > pandoc --version
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
...
raghu@desktop:~/code/mermaid-filter > mermaid --version
0.5.5
raghu@desktop:~/code/mermaid-filter > phantomjs --version
1.9.8
raghu@desktop:~/code/mermaid-filter > which mermaid-filter
/usr/bin/mermaid-filter
raghu@desktop:~/code/mermaid-filter > cat /usr/lib/node_modules/mermaid-filter/package.json |grep -i githead
  "gitHead": "99a7f7637026161988e86d2a4f51cf578e8cf818",
```

**Comment by josephwinston** [comment]
User error.  I had not updated pandoc.
