### ISSUE TITLE
Use newer mermaid.cli version

### ISSUE THREAD

**Issue by agusmba** [raghur/mermaid-filter#20]
Just a friendly reminder, so that I do not forget telling you in a few days.

Today I checked mermaid's latest developments and saw that mermaid.cli version 0.4.3 comes with new and better options.
It relies currently on mermaid v 8.0.beta.9 so it might make sense to just monitor it until core mermaid 8.0 is released.

Beware of potential breaking changes (I haven't read them in-depth)

**Comment by lunarcloud** [comment]
Current release is now 10.6.1 - the project is still at "~9"

**Comment by raghur** [comment]
done - new rev released on npm
