### ISSUE TITLE
there is a problem on installing mermaid-filter on win 10

### ISSUE THREAD

**Issue by shixuguo** [raghur/mermaid-filter#25]
there is the log
```
npm install --global mermaid-filter
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shixuguo\AppData\Roaming\npm-cache\_logs\2018-09-03T14_11_30_389Z-debug.log
```

how can i solve the problem?

**Comment by raghur** [comment]
@shixuguo I don't have win10 - but on win 8.1 I just installed fine...

BTW, from your error, it looks like an interrupted download or something. have you retried? is there anything useful in the log file?

**Comment by shixuguo** [comment]
I have solved the problem. 
It seems casued by GFW of China.
If any Chinese user want to solve the same problem,
please ref to https://www.jianshu.com/p/9859d486b90d and http://npm.taobao.org/
