### ISSUE TITLE
Saving image file breaks on Windows

### ISSUE THREAD

**Issue by kohenkatz** [raghur/mermaid-filter#29]
Example:

    ```{.mermaid caption="Example" loc=generated}
    sequenceDiagram
        Alice->>John: Hello John, how are you?
        John-->>Alice: Great!
    ```

Expected result: file is saved in `.\generated\`

Actual result: A file is there in `.\generated\`, but it has no contents, and an error message is shown in the console:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\moshe\AppData\Local\Temp\tmp-24436bl73Au0XPsB7.tmp.png'
Error running filter mermaid-filter.cmd:
Filter returned error status 1
```

The problem is in the `mv` function - the file is removed using `fs.unlinkSync` *before* the copy to the new location is complete. (On *nix systems this is not an issue because an open file handle remains valid after the file is gone, but that is not the case on Windows - there an open file handle is invalidated immediately when the file is deleted.)

The fix for this is very simple:

```
function mv(from, to) {
    var readStream = fs.createReadStream(from)
    var writeStream = fs.createWriteStream(to);

    readStream.on('close', () => {
        fs.unlinkSync(from);
    });

    readStream.pipe(writeStream)
}
```

This way the original is only unlinked once the `pipe` operation is complete.

**Comment by raghur** [comment]
Thanks for the bug and the explanation :). Much appreciated!

**Comment by agalunstop** [comment]
Hi
I am still getting this error. I installed Mermaid on mac using 
npm install --global mermaid-filter

and executed using
pandoc -t html -F mermaid-filter -o something.html new_trial.md
