### ISSUE TITLE
PNG file width is too small compared to mermaid.cli

### ISSUE THREAD

**Issue by pointbre** [raghur/mermaid-filter#32]
# Update
I've had a look at index.js about why width is always limited under 500px no matter .mermaid-config.json has width option.

* Width is populated from environmental variable `MERMAID_FILTER_WIDTH` or by default, 500: `width: process.env.MERMAID_FILTER_WIDTH || '500',`
* The width is used in command with a separate argument `-w` along with configuration file: `${cmd}  ${confFileOpts} ${puppeteerOpts} -w ${options.width} -i ${tmpfileObj.name} -t ${options.theme} -o ${savePath}`
* So, the value in .mermaid-config.json seems to be always overriden by `-w ${options.width}` which explains why generated image's width is < 500 px.
* A workaround would be setting MERMAID_FILTER_WIDTH before run pandoc with mermaid-filter like `MERMAID_FILTER_WIDTH=800 pandoc ... -F mermaid-filter ...`.

# Original
Hi, thanks for your project which enables me to use markdown for documentation easily. However, I've got an issue with width of mermaid diagram image. 

## Tested mermaid diagram
```
gantt
        dateFormat  YYYY-MM-DD
        title Adding GANTT diagram functionality to mermaid
        section A section
        Completed task            :done,    des1, 2014-01-06,2014-01-08
        Active task               :active,  des2, 2014-01-09, 3d
        Future task               :         des3, after des2, 5d
        Future task2               :         des4, after des3, 5d
        section Critical tasks
        Completed task in the critical line :crit, done, 2014-01-06,24h
        Implement parser and jison          :crit, done, after des1, 2d
        Create tests for parser             :crit, active, 3d
        Future task in critical line        :crit, 5d
        Create tests for renderer           :2d
        Add to mermaid                      :1d
```

## Comparison
![image](https://user-images.githubusercontent.com/28047477/55903290-6d5d0680-5c21-11e9-8c36-bb9832239b56.png)

## The first one
generated by mermaid-filter(recent version) like `pandoc -f gfm Markdown.md -F mermaid-filter -t html5 -H header.html --self-contained -o Markdown.html` without any css / json configuration files.

## The second one
generated by mermaid-cli(recent version) like `mmdc -i test.mmd -o test.png` without any command line arguments.

I'm not too sure how I can generate image like mermaid.cli does.

**Comment by raghur** [comment]
@pointbre  thank you for analysis in your update. Can you test `mmdc` cli directly with width both on as an argument and in a config json? Looking at mmdcs' source code here
https://github.com/mermaidjs/mermaid.cli/blob/master/index.js#L85

They seem to be setting viewport width and height only from CLI argument (or default) but not picking it up from the config json at all.

It does make sense to use the same defaults as mmdc though (width 800, height 600)

**Comment by pointbre** [comment]
@raghur You're absolutely right. 

* Only with configuration json file which has `"width": 2000`: width --> 784 px
* Only with command line argument `-w 1000`: width --> 984 px
* With configuration json file which has `"width": 2000` and command line argument `-w 1000`: width --> 984 px

In short, mermaid-cli doesn't take width from configuration json file.
