### ISSUE TITLE
Quotes make mermaid-filter hang forever

### ISSUE THREAD

**Issue by lopezator** [raghur/mermaid-filter#37]
Quotes are admited by mermaid to escape characters like stated here:

https://mermaidjs.github.io/#/flowchart?id=entity-codes-to-escape-characters

Unfortunately, using them inside a mermaid block, makes mermaid filter and pandoc to hang forever.

Example `.md` to reproduce the problem:

> ```mermaid
> graph LR;
>     A-->B;
>     click A callback "Tooltip for a callback"
>     click B "http://www.github.com" "This is a tooltip for a link"
> ```

Command used:

```
MERMAID_FILTER_FORMAT='svg' pandoc --verbose -V geometry:margin=1in --highlight-style haddock --standalone --self-contained --toc --top-level-division=chapter -f markdown -t latex -F mermaid-filter -o .artifacts/my-pdf.pdf rfc/my-md.md
```

Pandoc version:

```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/my.user/.local/share/pandoc or /Users/my.user/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by lopezator** [comment]
@raghur I still can reproduce the issue using `v1.4.2`. Can you confirm it's fixed?

**Comment by raghur** [comment]
hmm - I used your test diagram to verify and added it to test.md.

Can you confirm that you see a `mermaid-filter.err` being created (this is stderr being redirected to a file). Pandoc does not like it if there's anything on stdout other than valid pandoc JSON and hangs otherwise.

Also, can you confirm index.js file contents and that it's the right one being invoked?

**Comment by lopezator** [comment]
I add another example, the following mermaid code, enclosed in a `TEST.md` file.

```mermaid
graph TD
  subgraph "Destination"
    Foo
  end
```

Along with the following pandoc command:

```
MERMAID_FILTER_FORMAT='svg' pandoc --verbose -V geometry:margin=1in --highlight-style haddock --standalone --self-contained --toc --top-level-division=chapter -f markdown -t latex -F mermaid-filter -o my-pdf.pdf TEST.md
```

Creates an empty `mermaid-filter.err` file when executed and still hangs forever.

**Comment by raghur** [comment]
So this seems to be a slightly different manifestation of the same issue.

For the original issue you reported, I added it to the test.md that's in the repository and can be tested.

This new example with the subgraph and it does hang and there's nothing in the err file either.
Do note that I'm unable to run your command as is - I'm testing with just 

`pandoc -i test.md -F mermaid-filter.cmd -t html -o test.html`

I'll look into this more when I get time.

**Comment by lopezator** [comment]
We are using mermaid filter to automatically generate pdf's on a markdown repository ci builds and sometimes builds hang forever on CI because of this.

By the way, thank you @raghur for the help and your awesome work, I wish I could help with this, but I know nothing about JS.

**Comment by lopezator** [comment]
Hello @raghur we have found another problematic usecase.

If you write a simple mermaid `graph LR` like this:

> graph LR
>     A --> B --> C --> D

The tool also creates an empty `mermaid-filter.err` file, and hangs forever. 

I don't know if the cause could be the same or not, but this might be another good scenario to test.

In order to make this work and get the same output, we had to rewrite all of our graphs to include just a "command" per line like this:

> graph LR
>      A --> B 
>      B --> C
>      C --> D

**Comment by faxik** [comment]
This hit us today, as well... Did you have a time to look into it? Thank you for your work!

**Comment by raghur** [comment]
See - https://github.com/mermaidjs/mermaid.cli/issues/77

Both for this example and for the previous one with a subgraph quote, mermaid.cli errors out with a parse error and hangs. 
Its strange though since the live editor does not report a problem

**Comment by BeWe11** [comment]
Hey all,

I don't think the main problem here is that mermaid CLI hangs on syntax errors, but rather that mermaid-filter uses an outdated mermaid version that produces these syntax errors.

The [package.json](https://github.com/raghur/mermaid-filter/blob/master/package.json) file of mermaid-filter defines a mermaid version of `^7.1.2`, while the newest mermaid version is `8.4.8`.

After cloning mermaid-filter and manually bumping the major version of mermaid, I am able to render my mermaid graphs without hanging.

Is there a reason why mermaid-filter doesn't use mermaid `8.x.x`?

**Comment by faxik** [comment]
I confirm that with 8.4.4 no hangs occur.

**Comment by raghur** [comment]
Thanks folks... just updated package.json and published to npm
