### ISSUE TITLE
cannot configure graph background

### ISSUE THREAD

**Issue by indietyp** [raghur/mermaid-filter#38]
mermaid-cli allows you to set the background of the generated svg (https://github.com/mermaidjs/mermaid.cli#options) and defaults to white. mermaid-filter currently does not allow to set that option. This should probably change and could make mermaid-filter a lot more flexible and helpful in certain scenarios.

happy to create a pull request if necessary, but looking at the code - implementing this feature would be easy.

**Comment by raghur** [comment]
Doesn't the CSS file let you set the background color as well?

In any case, a PR will be appreciated.
