### ISSUE TITLE
Support output format=pdf for pandoc/pdf with high quality figure

### ISSUE THREAD

**Issue by wanghc78** [raghur/mermaid-filter#43]
Because pandoc pdf generation converts markdown figure as `\includegraphics{}`, which doesn't support svg format as input.

It will be very useful that mermaid-filter adds the support to generate pdf format, like

```{.mermaid format=pdf}
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```
The current fliter can still output pdf if I set `format=pdf loc=images`. The inline doesn't work.

**Comment by jogundas** [comment]
It would be a very useful feature for me too.

**Comment by pfaco** [comment]
Wonder if I'm missing something here, but it worked for me using "output=pdf" with pandoc.
The generated PDF is one full page long, no matter the actual diagram size. So I got a lot of white space. Any ideas if that's fixable?
