### ISSUE TITLE
Breaks with GitLab CI/CD Docker Container Registry

### ISSUE THREAD

**Issue by VincentTam** [raghur/mermaid-filter#51]
# Steps to reproduce error

1. Build Docker Container Registry with GitLab CI/CD ([my sample GitLab repo](https://gitlab.com/VincentTam/pandoc-mermaid-docker/tree/18f4950dfe5ef1ce3b438c98d97d1dd767414e59))
    - Dockerfile: https://gitlab.com/VincentTam/pandoc-mermaid-docker/-/blob/18f4950dfe5ef1ce3b438c98d97d1dd767414e59/Dockerfile, mainly copied from https://github.com/time-machine-project/requests-for-comments/blob/470b0c5fdb8c1375ab8726c86b453cb9945e4be2/build/Dockerfile, aims at installing the necessary dependencies without unrelated stuff like bash, python, etc.
    - GitLab CI/CD config: https://gitlab.com/VincentTam/pandoc-mermaid-docker/-/blob/18f4950dfe5ef1ce3b438c98d97d1dd767414e59/.gitlab-ci.yml, copied from https://gist.github.com/florentchauveau/2dc4da0299d42258606fc3b0e148fc07#file-gitlab-ci-yml, with some modifications to circumvent issue https://gitlab.com/gitlab-org/gitlab-foss/-/issues/65511
    - job succeeded: https://gitlab.com/VincentTam/pandoc-mermaid-docker/-/jobs/704412168

          Step 9/9 : RUN npm install eslint mermaid @mermaid-js/mermaid-cli mermaid-filter
           ---> Running in 108c4c485814
          npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
          npm WARN deprecated har-validator@5.1.5: this library is no longer supported
          > puppeteer@5.2.1 install /data/node_modules/puppeteer
          > node install.js
          **INFO** Skipping browser download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" environment variable was found.
          npm WARN saveError ENOENT: no such file or directory, open '/data/package.json'
          npm notice created a lockfile as package-lock.json. You should commit this file.
          npm WARN enoent ENOENT: no such file or directory, open '/data/package.json'
          npm WARN data No description
          npm WARN data No repository field.
          npm WARN data No README data
          npm WARN data No license field.
          + eslint@7.7.0
          + mermaid-filter@1.4.4
          + @mermaid-js/mermaid-cli@8.7.0
          + mermaid@8.7.0
          added 284 packages from 245 contributors and audited 286 packages in 17.171s
          14 packages are looking for funding
            run `npm fund` for details
          found 0 vulnerabilities

2. Compile a minimal sample Markdown file ([my sample GitLab repo](https://gitlab.com/VincentTam/test_pandoc/tree/b031a545d517061cde0dfe7b179b87cef47915df)) with a minimal GitLab CI config file.

    ```yaml
    image:
      name: registry.gitlab.com/vincenttam/pandoc-mermaid-docker
      entrypoint: [""]

    build:
      script:
        - mkdir public
        - pandoc README.md -o public/README.pdf -F mermaid-filter

      artifacts:
        paths:
        - public
    ```

# Error received

```
Executing "step_script" stage of the job script
00:01
$ mkdir public
$ pandoc README.md -o public/README.pdf -F mermaid-filter
internal/fs/utils.js:269
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/tmp/tmp-15k64lpMLghB1y.tmp.png'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at mermaid (/data/node_modules/mermaid-filter/index.js:83:27)
    at /data/node_modules/mermaid-filter/index.js:143:12
    at /data/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (/data/node_modules/pandoc-filter/index.js:50:7)
    at /data/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (/data/node_modules/pandoc-filter/index.js:73:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/tmp-15k64lpMLghB1y.tmp.png'
}
Error running filter mermaid-filter:
Filter returned error status 1
ERROR: Job failed: exit code 83
```

**Comment by raghur** [comment]
My apologies - but I don't have time to go through the entire chain. Do you have a minimal example with a failure that can be easily reproduced?
Superficially, you can check if you're able to run with the docker image locally. mermaid filter saves generated png in `/tmp` and in your case, it says the generated file isn't found. For all I know, Gitlab might be doing something dfiferent.

**Comment by VincentTam** [comment]
> My apologies - but I don't have time to go through the entire chain. Do you have a minimal example with a failure that can be easily reproduced?

To reproduce the error, you just need to fork my project, which has only 2-3 files (Dockerfile, GitLab CI/CD & README).  The text that follows simply explains where I grabbed these lines, and my modifications to their files (mainly to simply things/correct execution errors).


> Superficially, you can check if you're able to run with the docker image locally.

Lemme do that tonight when I've got WiFi.

**Comment by VincentTam** [comment]
For self-reference: Tested locally.  `mmdc` doesn't work on my machine, and that seems to be a compatibility problem between Chromium & https://github.com/puppeteer/puppeteer/releases/tag/v5.2.1.  The latest version for Alpine is still 84.0.4147.135-r0 from https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium.  Here's the guide from the node.js package: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine.

**Comment by VincentTam** [comment]
I've finally managed to get this work on GitLab CI.

:heavy_check_mark: Construction of the Docker image registry.gitlab.com/vincenttam/pandoc-mermaid-docker:96d2cc19d0572f1fc9b973cbb8882cfa4975a28c
:heavy_check_mark: Compilation of [my sample README.md](https://gitlab.com/VincentTam/test_pandoc/-/commit/28a63b6180958239e4cec042e0fc7d5c1502b07f)

The keys are

1. choosing the right version of Puppeteer & Chromium browser to install
2. finding a good config file from GitHub code search
