### ISSUE TITLE
External tool not found: mmdc

### ISSUE THREAD

**Issue by VincentTam** [raghur/mermaid-filter#52]
At job https://gitlab.com/VincentTam/test_pandoc/-/jobs/704713047, I'm working with a newer image
https://gitlab.com/VincentTam/pandoc-mermaid-docker/tree/1c1971477ddb5dd62eedd6d3c34228fe97194434
with necessary node.js packages installed globally.
The linked job shows that I have `/usr/bin/mmdc`, and `/usr/bin` is in the PATH, so I couldn't understand what happened.

**Comment by raghur** [comment]
it looks for mmdc in node_modules... please see index.js
