### ISSUE TITLE
EMFILE too many files when running on Windows 10

### ISSUE THREAD

**Issue by KennyMac70** [raghur/mermaid-filter#58]
I've hit this issue on Windows 10 using pandoc to translate to PDF.

I have a workaround which involves replacing line 5 of `mermaid-filter\index.js`  to use **graceful-fs** rather than **fs**.

This 'fixes' the issue...

Is this a change you would consider in a new release...?

**Comment by raghur** [comment]
That sounds like a bug though - any/all references I can find online around EMFILE suggest etiher to update node (posts are really old) and/or indicate that there's a bug... 

Please go ahead and send me a PR - I'll be happy to merge it in (and/or maybe find actually why its happeneing). I've never seen the error myself though.

**Comment by KennyMac70** [comment]
Will do.

I'll create an minimal project that exhibits the issue as well,and post that here if that helps...?

**Comment by KennyMac70** [comment]
I've debugged it and worked out that its a handle leak of the file that is used to redirect `stderr`.
I've subbed a PR that I've tested... File handles reduced from 8000+ to around 200.
