### ISSUE TITLE
poor image quality with pandoc

### ISSUE THREAD

**Issue by VincentTam** [raghur/mermaid-filter#62]
I'm using pandoc 2.11.2 with default PDF engine (pdflatex) to get a PDF from

~~~
Un diagramme de classe UML

```mermaid
classDiagram
  class MaEntité {
    + maCléPrimaire
    + monAttribut1
    + monAttribut2
  }
```
~~~

    pandoc foo.md -o foo.pdf -F mermaid-filter

I'm using mermaid-filter@1.4.5, with all dependencies installed.

Is there a way to improve the image's resolution?

![Screenshot from 2020-12-08 15-05-46](https://user-images.githubusercontent.com/5748535/101493846-df41a200-3966-11eb-9baf-5a9a85356c90.png)

The acute accent is blurred on GitLab CI output

![image](https://user-images.githubusercontent.com/5748535/101494176-495a4700-3967-11eb-8ff6-f6e3431dbfd6.png)

1. repo for my sample file: https://gitlab.com/VincentTam/test_pandoc
2. my pandoc+LuaLaTeX+mermaid+TeX Gyre+Noto Emoji Docker image: https://gitlab.com/VincentTam/pandoc-mermaid-docker/

**Comment by fdq09eca** [comment]
```{.mermaid format=svg}
classDiagram
  class MaEntité {
    + maCléPrimaire
    + monAttribut1
    + monAttribut2
  }
```
try?

**Comment by VincentTam** [comment]
> ```lisp
> ```{.mermaid format=svg}
> classDiagram
>   class MaEntité {
>     + maCléPrimaire
>     + monAttribut1
>     + monAttribut2
>   }
> ```
> ```
> 
> try?

:rocket: :v: :grinning:  Thank you very much!  The problem has gone after some package updates.

![image](https://user-images.githubusercontent.com/5748535/110044867-28c54180-7d4a-11eb-8672-8035e35280c5.png)
![image](https://user-images.githubusercontent.com/5748535/110044951-42ff1f80-7d4a-11eb-9ec7-2213074f56a9.png)

**Comment by pabloazurduy** [comment]
hey, I tried using the `SVG` format 

```{.mermaid format=svg}
classDiagram
  class MaEntité {
    + maCléPrimaire
    + monAttribut1
    + monAttribut2
  }
```

but for some reason, the figure appears without the text. 

<img width="269" alt="image" src="https://user-images.githubusercontent.com/24685386/185154312-6a67f88d-5fb5-4aae-bd1f-bc14a26b5723.png">

Using the regular format it works fine but with low resolution 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/24685386/185154567-59e0fd6d-97cf-4080-b553-c450314cacab.png">

any ideas ?

**Comment by leg7** [comment]
> hey, I tried using the `SVG` format
> 
> ```mermaid
> classDiagram
>   class MaEntité {
>     + maCléPrimaire
>     + monAttribut1
>     + monAttribut2
>   }
> ```
> 
> but for some reason, the figure appears without the text.
> 
> <img alt="image" width="269" src="https://user-images.githubusercontent.com/24685386/185154312-6a67f88d-5fb5-4aae-bd1f-bc14a26b5723.png">
> 
> Using the regular format it works fine but with low resolution <img alt="image" width="329" src="https://user-images.githubusercontent.com/24685386/185154567-59e0fd6d-97cf-4080-b553-c450314cacab.png">
> 
> any ideas ?

I have the same issue.

**Comment by jobatabs** [comment]
Hi, I have this issue as well.
Clean lines, but no text:
![image](https://github.com/user-attachments/assets/133acbe9-9b73-4044-981b-9dc605130da6)
Text appears but image is low resolution:
![image](https://github.com/user-attachments/assets/beafc09f-87b1-4920-932a-747fe5bbb5b7)

**Comment by aleddaheig** [comment]
See https://github.com/jgm/pandoc/issues/8176#issuecomment-1866423703
