### ISSUE TITLE
Does this work for pdf output?

### ISSUE THREAD

**Issue by didibus** [raghur/mermaid-filter#8]
When I try this in pdf output, I don't see a diagram, just the code block I entered parsed as markdown. Actually, I see that also in html output.

**Comment by didibus** [comment]
It does work for PDF output also. The issue was that the example on the github readme is a bit misleading, it should be:

```
~~~mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
~~~
```

If you are using pandoc markdown with default extensions.

**Comment by t-power89** [comment]
I can get a pdf output can you please provide an example of your build command you use for this?
