### ISSUE TITLE
Filter fails with config or CSS file when path has spaces

### ISSUE THREAD

**Issue by ryanmahan** [raghur/mermaid-filter#84]
When the path to a `.mermaid.css` or `.mermaid-config.json` file contains a space, the command run does not include handling the space and fails.

Steps to reproduce:
1. Create a folder with a space in it
2. Create md file and CSS or JSON file in the folder
3. Run pandoc with the filter so it uses the CSS or JSON file

The `-c /path/to/file/with space/.mermaid.css` argument will cause the command to fail

**Comment by raghur** [comment]
That's the shell though - if your path has spaces, then either you need to escape the path (on linux) or quote it (linux/windows)...

**Comment by ryanmahan** [comment]
Sorry it's been a while since I wrote this report, but if I remember correctly it happens with relative paths as well. Like if I just did ./mermaid.css and my pwd was a folder with a space.

**Comment by raghur** [comment]
should be fixed by #92
