### ISSUE TITLE
Error running filter mermaid-filter.cmd  terminateProcess: permission denied (Permission denied)

### ISSUE THREAD

**Issue by didibus** [raghur/mermaid-filter#9]
I'm getting a permission denied when running: `mermaid-filter.cmd` on windows.

Any idea why?

**Comment by didibus** [comment]
After changing the .cmd file to not use ~dp0, but instead hard-code the real path on my computer, the permissionDenied error disappeared.

I now get this error: `pandoc: Error in $: Failed reading: not a valid json value CallStack (from HasCallStack): error, called at pandoc.hs:144:42 in main:Main`

**Comment by raghur** [comment]
Are you on windows 8.1? Try this (is in the readme)
>Windows 8.1 - On windows 8.1, mermaid-filter.cmd fails - apparently due to change in how the CMD.exe works for subprocesses? - see this issue thread. You have to edit the globally installed mermaid-filter.cmd located in c:\users\<username>\AppData\Roaming\npm to use ~dp$PATH:0. Unfortunately, you will need to do this each time you install/update mermaid-filter since it overwrites the cmd file.

**Comment by raghur** [comment]
What version of pandoc do you have?

**Comment by didibus** [comment]
I have pandoc 1.19.2.1 on Windows 7.

I tried the ~dp$PATH:0 change, and it works. Maybe later Windows 7 updates have back-ported some of the Windows 8.1 changes. So if anyone else is having this issue, I suggest following the same process just in case, even on a different version of Windows.
